import { computed, defineComponent, onMounted, ref, watch } from "vue";

type Visit = { id: number; date: string; companions: string; event: string };
type FoodRecord = {
  id: number; name: string; shop: string; address: string;
  coordinates: { lat: number; lng: number }; map: { x: number; y: number };
  visited: boolean; visits: Visit[];
  attributes: { category: string; ingredient: string; form: string; flavors: string[]; cuisine: string | null };
  rating: { overall: number; taste: number; value: number; environment: number };
  review: string; emoji: string; color: string;
};

const importedVisit=(id:number,name:string,place:string,date:string,category:string,ingredient:string,form:string,flavors:string[],cuisine:string|null,lat:number,lng:number,x:number,y:number,emoji:string):FoodRecord=>({
  id,name,shop:name,address:`北京 · ${place}`,coordinates:{lat,lng},map:{x,y},visited:true,
  visits:[{id,date,companions:"",event:"到访记录已导入；同行人和当时发生的事情待补充。"}],
  attributes:{category,ingredient,form,flavors,cuisine},rating:{overall:0,taste:0,value:0,environment:0},
  review:"个人评价待补充。",emoji,color:"#e98772"
});

const seed: FoodRecord[] = [
  importedVisit(101,"环球大道影城","环球影城度假区","2026-08-22","其他","具体餐食待补充","度假区逛吃",[],null,39.8557,116.6747,88,18,"🎬"),
  importedVisit(102,"SHAKE SHACK","合生汇","2026-08-22","主食","牛肉、面包","汉堡",["咸鲜","肉香"],"美式",39.8944,116.4764,72,24,"🍔"),
  importedVisit(103,"面包师农场","北新桥","2026-08-22","烘焙","面粉、黄油","面包",["麦香","烘焙香"],null,39.9410,116.4166,29,19,"🥖"),
  importedVisit(104,"24个面包师","北新桥","2026-08-22","烘焙","面粉、黄油","面包",["麦香","烘焙香"],null,39.9410,116.4166,35,28,"🥐"),
  importedVisit(105,"美珍香","荟聚","2026-08-23","零食","猪肉","肉脯",["甜","咸鲜","烟熏"],null,39.7949,116.3282,22,62,"🥓"),
  importedVisit(106,"北冰洋","荟聚","2026-08-23","饮品","橙汁、碳酸水","汽水",["甜","橙香","气泡感"],null,39.7949,116.3282,31,72,"🥤"),
  importedVisit(107,"椿天熟成","荟聚","2026-08-23","饮品","茶、牛奶","奶茶",["奶香","茶香"],null,39.7949,116.3282,43,63,"🧋"),
  importedVisit(108,"孤独的寿喜烧","荟聚","2026-08-23","肉类","牛肉、蔬菜","寿喜烧",["甜咸","鲜香"],"日式",39.7949,116.3282,52,75,"🍲"),
  importedVisit(109,"汕心","荟聚","2026-08-23","主食","具体菜品待补充","潮汕料理",["咸鲜"],"潮汕菜",39.7949,116.3282,62,63,"🍚"),
  importedVisit(110,"吉屋出猪","荟聚","2026-08-23","肉类","猪肉","猪肉料理",["咸鲜","肉香"],null,39.7949,116.3282,70,73,"🐷"),
  importedVisit(111,"琦本的店","荟聚","2026-08-23","烘焙","具体原料待补充","面包",[],null,39.7949,116.3282,79,62,"🍞"),
  importedVisit(112,"山姆","具体门店待补充","2026-08-23","其他","具体餐食待补充","会员店采购与试吃",[],null,39.9042,116.4074,87,72,"🛒"),
  {id:113,name:"三出山",shop:"三出山",address:"北京 · 荟聚",coordinates:{lat:39.7949,lng:116.3282},map:{x:57,y:57},visited:false,visits:[],attributes:{category:"其他",ingredient:"具体餐食待补充",form:"具体做法待补充",flavors:[],cuisine:null},rating:{overall:0,taste:0,value:0,environment:0},review:"想去吃；具体菜品和评价待补充。",emoji:"🍽️",color:"#d9a15f"},
  {id:114,name:"胡恰",shop:"胡恰",address:"北京 · 荟聚",coordinates:{lat:39.7949,lng:116.3282},map:{x:66,y:55},visited:false,visits:[],attributes:{category:"其他",ingredient:"具体餐食待补充",form:"具体做法待补充",flavors:[],cuisine:null},rating:{overall:0,taste:0,value:0,environment:0},review:"想去吃；具体菜品和评价待补充。",emoji:"🍽️",color:"#d9a15f"}
];
const categoryIcons: Record<string,string>={全部:"✦",肉类:"🍖",饮品:"🧋",主食:"🍚",烘焙:"🥐",零食:"🍪",甜品:"🍰",其他:"🍽️"};
const emptyForm=()=>({name:"",shop:"",address:"",lat:"",lng:"",visited:false,date:"",companions:"",event:"",category:"肉类",ingredient:"",form:"",flavors:"",cuisine:"",overall:4.5,review:""});

export default defineComponent({setup(){
 const records=ref<FoodRecord[]>([...seed]),category=ref("全部"),query=ref(""),selected=ref(101),favorites=ref<number[]>([]),status=ref("全部"),view=ref<"map"|"list">("map"),modal=ref(false),form=ref(emptyForm());
 onMounted(()=>{records.value=[...seed]});
 watch(records,v=>localStorage.setItem("coco-food-records",JSON.stringify(v)),{deep:true});
 const categories=computed(()=>["全部",...Array.from(new Set(records.value.map(f=>f.attributes.category)))]);
 const visible=computed(()=>records.value.filter(f=>{const q=query.value.trim().toLowerCase(),hay=[f.name,f.shop,f.address,f.attributes.category,f.attributes.ingredient,f.attributes.form,...f.attributes.flavors,f.attributes.cuisine||"",f.review,...f.visits.map(v=>v.event)].join(" ").toLowerCase();return(category.value==="全部"||f.attributes.category===category.value)&&(status.value==="全部"||(status.value==="已去过"?f.visited:!f.visited))&&(!q||hay.includes(q))}));
 const chosen=computed(()=>records.value.find(f=>f.id===selected.value)),visitedCount=computed(()=>records.value.filter(f=>f.visited).length);
 const heart=(id:number)=>favorites.value=favorites.value.includes(id)?favorites.value.filter(x=>x!==id):[...favorites.value,id];
 const save=()=>{const f=form.value;if(!f.name.trim()||!f.shop.trim()||!f.address.trim())return;const id=Date.now(),lat=Number(f.lat)||23.1291,lng=Number(f.lng)||113.2644;records.value.push({id,name:f.name.trim(),shop:f.shop.trim(),address:f.address.trim(),coordinates:{lat,lng},map:{x:12+Math.random()*76,y:15+Math.random()*68},visited:f.visited,visits:f.visited&&f.date?[{id,date:f.date,companions:f.companions,event:f.event}]:[],attributes:{category:f.category,ingredient:f.ingredient,form:f.form,flavors:f.flavors.split(/[、,，]/).map(x=>x.trim()).filter(Boolean),cuisine:f.cuisine||null},rating:{overall:Number(f.overall),taste:Number(f.overall),value:Number(f.overall),environment:Number(f.overall)},review:f.review,emoji:categoryIcons[f.category]||"🍽️",color:"#e98772"});selected.value=id;modal.value=false;category.value="全部"};
 return()=> <main>
  <header class="topbar"><a class="brand" href="#"><i>♡</i><span><b>coco’s food map</b><small>我们的好吃备忘录</small></span></a><label class="search">⌕<input v-model={query.value} placeholder="搜美食、店铺、口味或回忆…"/><kbd>⌘ K</kbd></label><div class="actions"><button>♡</button><button class="add" onClick={()=>{form.value=emptyForm();modal.value=true}}>＋ 记一口好吃的</button><span>🐰</span></div></header>
  <section class="hero"><div><label>♡ FOOD · PLACE · MEMORY</label><h1>每一口好吃的，<br/><em>都有地点和故事。</em></h1><p>记下坐标、店铺、那天发生的事，也记住味道带来的心情。</p><div class="stats"><span><b>{records.value.length}</b> 个美食</span><span><b>{visitedCount.value}</b> 家去过</span><span><b>{records.value.reduce((n,f)=>n+f.visits.length,0)}</b> 段回忆</span></div></div><article class="surprise"><i>📍</i><div><small>选中的味觉记忆</small><strong>{chosen.value?.name}</strong><p>{chosen.value?.shop} · {chosen.value?.attributes.flavors.join(" / ")}</p></div><button onClick={()=>view.value="map"}>地图查看 →</button></article></section>
  <section class="content"><aside class="filters"><Title text="按种类找" tip={`${records.value.length} 个宝藏`}/><nav>{categories.value.map(n=><button class={{active:category.value===n}} onClick={()=>category.value=n}><i>{categoryIcons[n]||"🍽️"}</i><b>{n}</b><small>{n==="全部"?records.value.length:records.value.filter(f=>f.attributes.category===n).length}</small></button>)}</nav><hr/><Title text="到访状态" tip="计划与回忆"/><div class="status-filter">{["全部","已去过","想去吃"].map(s=><button class={{active:status.value===s}} onClick={()=>status.value=s}>{s==="已去过"?"✓ ":s==="想去吃"?"○ ":""}{s}</button>)}</div><article class="note">💌 <span><b>记录不止是评分</b><small>店铺和坐标定位味道<br/>到访故事保存那天的心情</small></span></article></aside>
   <section class="map"><header><span><b>{view.value==="map"?"好吃地图":"美食清单"}</b><small>{visible.value.length} 个地点正在召唤你</small></span><div><button class={{active:view.value==="map"}} onClick={()=>view.value="map"}>⌖ 地图</button><button class={{active:view.value==="list"}} onClick={()=>view.value="list"}>☷ 列表</button></div></header>{view.value==="map"?<div class="mapbody"><i class="road r1"/><i class="road r2"/><i class="river"/><label class="a1">老 城 区</label><label class="a2">甜 蜜 湾</label>{visible.value.map(f=><button class={{pin:true,active:selected.value===f.id,unvisited:!f.visited}} style={{left:`${f.map.x}%`,top:`${f.map.y}%`,background:f.color}} onClick={()=>selected.value=f.id}><span>{f.emoji}</span><b>{f.name}</b></button>)}{!visible.value.length&&<Empty/>}<div class="legend"><span>● 已吃过</span><span>○ 想去吃</span></div></div>:<div class="food-list">{visible.value.map(f=><article onClick={()=>selected.value=f.id} class={{active:selected.value===f.id}}><i style={{background:f.color}}>{f.emoji}</i><span><b>{f.name}</b><small>{f.shop} · {f.address}</small><p>{f.attributes.ingredient} · {f.attributes.flavors.join(" / ")}</p></span><em>{f.visited?"已去过":"想去吃"}</em></article>)}{!visible.value.length&&<Empty/>}</div>}</section>
   <aside class="detail">{chosen.value?<FoodDetail food={chosen.value} liked={favorites.value.includes(chosen.value.id)} onHeart={()=>heart(chosen.value!.id)}/>:<Empty/>}</aside></section><footer><b>Made with ♡ for 小馋猫</b><span>下一站，也要一起吃很多很多顿饭。 🍓</span></footer>
  {modal.value&&<div class="modal-mask" onClick={e=>{if(e.target===e.currentTarget)modal.value=false}}><form class="food-form" onSubmit={e=>{e.preventDefault();save()}}><header><span><small>NEW FOOD MEMORY</small><b>记一口好吃的</b></span><button type="button" onClick={()=>modal.value=false}>×</button></header><div class="form-grid"><Field label="美食名称 *"><input v-model={form.value.name} required placeholder="比如：蜜汁叉烧"/></Field><Field label="店铺名称 *"><input v-model={form.value.shop} required placeholder="在哪里吃到的"/></Field><Field label="详细地址 *" wide><input v-model={form.value.address} required placeholder="街道、商场、楼层…"/></Field><Field label="纬度"><input v-model={form.value.lat} type="number" step="any" placeholder="23.1291"/></Field><Field label="经度"><input v-model={form.value.lng} type="number" step="any" placeholder="113.2644"/></Field><Field label="种类"><select v-model={form.value.category}>{["肉类","饮品","主食","烘焙","零食","甜品","其他"].map(x=><option>{x}</option>)}</select></Field><Field label="主要原料"><input v-model={form.value.ingredient} placeholder="猪肉 / 牛奶 / 咖啡豆"/></Field><Field label="形态 / 做法"><input v-model={form.value.form} placeholder="烧腊 / 拿铁 / 烘焙"/></Field><Field label="口味标签"><input v-model={form.value.flavors} placeholder="酸、甜、辣、奶香…"/></Field><Field label="菜系（可空）"><input v-model={form.value.cuisine} placeholder="粤菜 / 川菜 / 西餐"/></Field><Field label="总评分"><input v-model={form.value.overall} type="number" min="1" max="5" step="0.1"/></Field></div><label class="check"><input type="checkbox" v-model={form.value.visited}/> 我已经去过这家店</label>{form.value.visited&&<div class="visit-fields"><Field label="到访日期"><input type="date" v-model={form.value.date}/></Field><Field label="同行的人"><input v-model={form.value.companions} placeholder="和谁一起"/></Field><Field label="当时发生的事" wide><textarea v-model={form.value.event} placeholder="记录那天特别的人、事和心情…"/></Field></div>}<Field label="我的评价"><textarea v-model={form.value.review} placeholder="味道、分量、环境，以及任何想记住的细节…"/></Field><button class="submit" type="submit">保存这段味觉记忆</button></form></div>}
 </main>
}});

const Title=defineComponent({props:{text:String,tip:String},setup(p){return()=> <div class="title"><b>{p.text}</b><small>{p.tip}</small></div>}});
const Empty=defineComponent({setup(){return()=> <div class="empty">🍽️<b>这里还没有记录</b><small>换个筛选条件，或记下新的好吃吧</small></div>}});
const Field=defineComponent({props:{label:String,wide:Boolean},setup(p,{slots}){return()=> <label class={{field:true,wide:p.wide}}><span>{p.label}</span>{slots.default?.()}</label>}});
const FoodDetail=defineComponent({props:{food:{type:Object as ()=>FoodRecord,required:true},liked:Boolean},emits:["heart"],setup(p,{emit}){const score=(n:number)=>n?n.toFixed(1):"待评分";return()=> <><div class="detail-head"><span><small>FOOD PROFILE</small><b>味觉档案</b></span><button class={{liked:p.liked}} onClick={()=>emit("heart")}>{p.liked?"♥":"♡"}</button></div><article class="food-hero"><i style={{background:p.food.color}}>{p.food.emoji}</i><span><label>{p.food.visited?"✓ 已去过":"○ 想去吃"}</label><h2>{p.food.name}</h2><p>{p.food.rating.overall?`★ ${score(p.food.rating.overall)}`:"☆ 待评分"} · {p.food.attributes.category}</p></span></article><section class="place-info"><small>店铺与地点</small><b>{p.food.shop}</b><p>📍 {p.food.address}</p><code>{p.food.coordinates.lat.toFixed(4)}, {p.food.coordinates.lng.toFixed(4)}</code></section><section><small class="section-label">味道属性</small><div class="chips"><b>{p.food.attributes.ingredient||"原料待补充"}</b><b>{p.food.attributes.form||"做法待补充"}</b>{p.food.attributes.cuisine&&<b>{p.food.attributes.cuisine}</b>}{p.food.attributes.flavors.map(x=><span>{x}</span>)}</div></section><section class="ratings"><small class="section-label">我的评分</small><div><span>味道 <b>{score(p.food.rating.taste)}</b></span><span>性价比 <b>{score(p.food.rating.value)}</b></span><span>环境 <b>{score(p.food.rating.environment)}</b></span></div><blockquote>“{p.food.review||"还没有写评价"}”</blockquote></section><section class="memory"><small class="section-label">到访与故事 · {p.food.visits.length}</small>{p.food.visits.length?p.food.visits.map(v=><article><i>♡</i><span><b>{v.date} {v.companions&&`· ${v.companions}`}</b><p>{v.event||"这一天还没有写下故事。"}</p></span></article>):<p class="not-visited">还没去过，把它留在下一站清单里。</p>}</section></>}});
